In [152]:
import pandas as pd
from pathlib import Path
import sys
import os
sys.path.append('../../Brian')
from yahoo_api import *

In [153]:
def get_MC_input(Monte_Carlo_df, portfolios, portfolio, init_investment, invest_period):
    portfolio_df=portfolios.loc[:,portfolio]
    portfolio_df=portfolio_df[portfolio_df > 0]
    portfolio_df=portfolio_df.to_frame('weights')
    symbols=list(portfolio_df.index)
    weights=list(portfolio_df['weights'])
    MC_df=Monte_Carlo_df.loc[:,symbols]
    return [MC_df, weights, init_investment, invest_period]

In [156]:
# Read the the ny_places_interest.csv file into a DataFrame
portfolios = pd.read_csv(Path("Portfolios.csv"))
portfolios=portfolios.set_index('Ticker')
# Review the DataFrame
portfolios

         Risk Capacity  Risk Tolerance  Benchmark  Cryptomix
Ticker
BTC-USD       0.212815        0.551077   0.532337   0.742584
ETH-USD       0.835128        0.659002   0.572224   0.219586
SQ            0.341948        0.665209   0.672914   0.770282
SHOP          0.564393        0.751846   0.241575   0.368560
TSLA          0.933267        0.041617   0.085270   0.314733
NVDA          0.120167        0.806750   0.233535   0.044073
AAPL          0.132851        0.666972   0.254310   0.385282
GOOG          0.994913        0.097304   0.585566   0.634796
MSFT          0.587720        0.342197   0.038299   0.838989
XOM           0.522416        0.668830   0.276739   0.919309
T             0.937829        0.258753   0.977117   0.938741
JPM           0.216766        0.550176   0.539446   0.447158
TLT           0.432765        0.715202   0.899050   0.263914
IEF           0.761212        0.795183   0.565055   0.003744
VGSH          0.450071        0.036545   0.059156   0.560244
SPY           0.786486        0.197958   0.313707   0.803626
AGG           0.007243        0.445198   0.440449   0.596019

In [157]:
tickers = list(portfolios.index)

In [158]:
portfolio_names=portfolios.columns.to_list()
portfolio_names

['Risk Capacity', 'Risk Tolerance', 'Benchmark', 'Cryptomix']

In [159]:
portfolios_dict={}
for ticker in tickers:
    portfolios_dict[ticker]=1/len(tickers)
display(portfolios_dict)

{'BTC-USD': 0.058823529411764705,
 'ETH-USD': 0.058823529411764705,
 'SQ': 0.058823529411764705,
 'SHOP': 0.058823529411764705,
 'TSLA': 0.058823529411764705,
 'NVDA': 0.058823529411764705,
 'AAPL': 0.058823529411764705,
 'GOOG': 0.058823529411764705,
 'MSFT': 0.058823529411764705,
 'XOM': 0.058823529411764705,
 'T': 0.058823529411764705,
 'JPM': 0.058823529411764705,
 'TLT': 0.058823529411764705,
 'IEF': 0.058823529411764705,
 'VGSH': 0.058823529411764705,
 'SPY': 0.058823529411764705,
 'AGG': 0.058823529411764705}

In [160]:
API_call=dataframe_maker(portfolios_dict)

KeyError: 'items'

In [ ]:
Monte_Carlo_df=API_call['Historical prices']
display(Monte_Carlo_df.head())
display(Monte_Carlo_df.tail())

In [ ]:
daily_returns_df=API_call['Daily returns']
display(daily_returns_df.head())
display(daily_returns_df.tail())

In [138]:
closing_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1310 entries, 11-08-2017 to 01-24-2023
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BTC-USD  1310 non-null   float64
 1   ETH-USD  1310 non-null   float64
 2   T        1310 non-null   float64
 3   XOM      1310 non-null   float64
 4   AAPL     1310 non-null   float64
 5   MSFT     1310 non-null   float64
 6   SQ       1310 non-null   float64
 7   AGG      1310 non-null   float64
 8   SPY      1310 non-null   float64
dtypes: float64(9)
memory usage: 134.6+ KB

In [139]:
daily_returns_df=closing_prices_df.pct_change().dropna()

In [140]:
daily_returns_df

,BTC-USD,ETH-USD,T,XOM,AAPL,MSFT,SQ,AGG,SPY
date,,,,,,,,,
11-09-2017,-0.073554,-0.067408,0.016627,0.005990,-0.002043,-0.005558,0.034051,-0.000731,-0.003628
11-10-2017,-0.039368,0.051562,0.006620,-0.012266,-0.006823,-0.002616,0.032929,-0.004021,-0.000310
11-13-2017,0.043751,0.072931,-0.001547,-0.000603,-0.004122,0.000715,0.019638,0.000000,0.000930
11-14-2017,0.102444,-0.012647,-0.013173,-0.007842,-0.015176,0.001430,-0.006003,0.001009,-0.002323
11-15-2017,0.076023,-0.007319,0.002748,-0.012524,-0.013075,-0.012731,0.023150,0.001925,-0.005005
...,...,...,...,...,...,...,...,...,...
01-18-2023,0.019238,0.024447,-0.016037,-0.020544,-0.005370,-0.018889,-0.039814,0.009926,-0.015788
01-19-2023,0.075391,0.069041,-0.004206,0.006419,0.000444,-0.016454,-0.016225,-0.002283,-0.007280
01-20-2023,0.004457,-0.019660,0.015312,0.018236,0.019221,0.035744,0.073583,-0.004080,0.018629
01-23-2023,-0.006197,-0.043340,-0.006760,-0.005205,0.023500,0.009824,0.072216,-0.002498,0.011999
01-24-2023,0.021266,0.035404,0.003141,0.009312,0.010063,-0.002226,-0.010654,0.004407,-0.001073

In [141]:
init_investment = 10000
invest_period=2

In [142]:
portfolios

          P1   P2   P3   P4
Ticker
BTC-USD  0.2  0.0  0.1  0.0
ETH-USD  0.3  0.4  0.3  0.0
T        0.1  0.0  0.0  0.5
XOM      0.0  0.5  0.0  0.4
AAPL     0.3  0.0  0.0  0.0
MSFT     0.1  0.0  0.0  0.0
SQ       0.0  0.0  0.5  0.0
AGG      0.0  0.1  0.0  0.0
SPY      0.0  0.0  0.1  0.1

In [143]:
#using get_breakdowns function above create a list of breakdown by sector, industry, ticker name and market cap
Monte_Carlo__list=[get_MC_input(Monte_Carlo_df, portfolios, portfolio, init_investment, invest_period) for portfolio in portfolio_names]

In [144]:
display(Monte_Carlo__list[3][0])

                T                                     XOM                  \
             open   high    low  close     volume    open    high     low
date
11-08-2017  24.81   25.3  24.76  25.26  115981341   83.36    83.5   82.86
11-09-2017  25.25  26.02  25.19  25.68   92568652    83.3   84.14   83.08
11-10-2017  25.81  26.04  25.76  25.85   76099018   83.01   83.08   82.42
11-13-2017  25.89  25.95  25.79  25.81   38213023   82.65   83.09    82.6
11-14-2017  25.82  25.83  25.36  25.47   40065829   82.42   82.75   82.09
...           ...    ...    ...    ...        ...     ...     ...     ...
01-19-2023  18.93  19.02  18.79  18.94   40180800  110.07  112.13  109.58
01-20-2023  18.96  19.23  18.77  19.23   37831200  111.36  113.44  110.61
01-23-2023  19.23   19.4  18.98   19.1   32890800  113.64  114.59  112.64
01-24-2023  18.97  22.84  15.15  19.16   32858500  109.16  114.02   99.23
01-26-2023  20.27  20.32  19.81  19.92   25168724  114.72  117.14  114.33

                                 SPY
             close    volume    open    high     low   close    volume
date
11-08-2017   83.47   8691600  258.47  259.22  258.15  259.11  50469600
11-09-2017   83.97  10528800  257.73  258.39  256.36  258.17  95085500
11-10-2017   82.94   8693700  257.73  258.29  257.37  258.09  59984700
11-13-2017   82.89   6720400  257.31  258.59  257.27  258.33  50228600
11-14-2017   82.24   9251700  257.41  257.85  256.52  257.73  61315200
...            ...       ...     ...     ...     ...     ...       ...
01-19-2023  111.32  12928000  389.36  391.08  387.26  388.64  86958900
01-20-2023  113.35  16481400   390.1  396.04  388.38  395.88  91544900
01-23-2023  112.76  16584400  396.72  402.65  395.72  400.63  84178800
01-24-2023  113.81  13583100  398.88  401.15  397.64   400.2  59524900
01-26-2023  116.96  11985401  403.13  404.07  400.03  403.14  40225465

[1311 rows x 15 columns]

In [145]:
p1_df=portfolios.loc[:,'P1']
p1_df=p1_df[p1_df > 0]
p1_df

Ticker
BTC-USD    0.2
ETH-USD    0.3
T          0.1
AAPL       0.3
MSFT       0.1
Name: P1, dtype: float64

In [146]:
p1_df=p1_df.to_frame('weights')

In [147]:
symbols=list(p1_df.index)
weights=list(p1_df['weights'])
display(symbols)
display(weights)

['BTC-USD', 'ETH-USD', 'T', 'AAPL', 'MSFT']

[0.2, 0.3, 0.1, 0.3, 0.1]

In [148]:
MC_df=Monte_Carlo_df.loc[:,symbols]

In [149]:
MC_df

             BTC-USD                                             ETH-USD  \
                open      high       low     close       volume     open
date
11-08-2017   7446.83   7446.83   7101.52   7143.58   3226249984   308.64
11-09-2017   7173.73      7312   6436.87   6618.14   5208249856   320.67
11-10-2017   6618.61   6873.15   6204.22    6357.6   4908680192   298.59
11-13-2017   6561.48   6764.98   6461.75   6635.75   3197110016   316.76
11-14-2017   6634.76   7342.25   6634.76   7315.54   4200880128   337.96
...              ...       ...       ...       ...          ...      ...
01-19-2023  21085.37  22692.36  20919.13  22676.55  28799154319  1552.37
01-20-2023  22677.43  23282.35  22511.83  22777.63  32442278429  1659.71
01-23-2023  22929.63  23134.01  22549.74  22636.47  26405069715  1627.85
01-24-2023  22639.27   23722.1  22406.08  23117.86  30685366709  1556.81
01-26-2023  23128.99  23235.38  22915.83  23066.56  33382842368  1613.23

                                                    ...    AAPL          \
               high      low    close       volume  ...    open    high
date                                                ...
11-08-2017   329.45   307.06   320.88    893249984  ...   43.67   44.06
11-09-2017   324.72   294.54   299.25    885985984  ...   43.78   44.03
11-10-2017   319.45   298.19   314.68    842300992  ...   43.78   43.85
11-13-2017   340.18   316.76   337.63   1069680000  ...   43.38   43.63
11-14-2017   340.91   329.81   333.36    722665984  ...   43.26   43.37
...             ...      ...      ...          ...  ...     ...     ...
01-19-2023  1659.89  1544.92  1659.75   8528894754  ...  134.08  136.25
01-20-2023  1674.18  1626.81  1627.12   8859250310  ...  135.28  138.02
01-23-2023  1639.72  1551.39   1556.6   8180274691  ...  138.12  143.32
01-24-2023  1632.24   1530.8  1611.71  10598973448  ...  140.31  143.16
01-26-2023   1626.2  1587.43  1602.66  10836733952  ...  143.17  144.25

                                         MSFT                          \
               low   close     volume    open    high     low   close
date
11-08-2017   43.58   44.06   97638000   84.14   84.61   83.83   84.56
11-09-2017   43.28   43.97  117930400   84.11   84.27    82.9   84.09
11-10-2017   43.57   43.67  100582000   83.79    84.1   83.23   83.87
11-13-2017   43.35   43.49   67928400   83.66   83.94   83.46   83.93
11-14-2017   42.79   42.83   99130000    83.5    84.1   82.98   84.05
...            ...     ...        ...     ...     ...     ...     ...
01-19-2023  133.77  135.27   58280400  233.78  235.52  230.68  231.93
01-20-2023  134.22  137.87   79972200  234.86  240.74  234.51  240.22
01-23-2023   137.9  141.11   81760300   241.1  245.17  239.65  242.58
01-24-2023   140.3  142.53   66435100   242.5  243.95  240.44  242.04
01-26-2023   141.9  143.19   31742455  243.65  246.06  242.01  244.93


              volume
date
11-08-2017  18034200
11-09-2017  21178400
11-10-2017  19397800
11-13-2017  14196900
11-14-2017  18801300
...              ...
01-19-2023  28623000
01-20-2023  35323400
01-23-2023  31934000
01-24-2023  40234400
01-26-2023  18724268

[1311 rows x 25 columns]

In [150]:
portfolios_returns=daily_returns_df.dot(portfolios)

In [151]:
portfolios_returns

                  P1        P2        P3        P4
date
11-09-2017 -0.034439 -0.024041 -0.010915  0.010347
11-10-2017  0.005949  0.014090  0.027966 -0.001628
11-13-2017  0.029310  0.028871  0.036166 -0.000922
11-14-2017  0.010968 -0.008879  0.003217 -0.009956
11-15-2017  0.008088 -0.008997  0.016481 -0.004136
...              ...       ...       ...       ...
01-18-2023  0.006078  0.000500 -0.012228 -0.017815
01-19-2023  0.033858  0.030597  0.019411 -0.000263
01-20-2023  0.005865  0.000846  0.033202  0.016813
01-23-2023 -0.006885 -0.020188  0.023686 -0.004262
01-24-2023  0.017985  0.019258  0.007314  0.005188

[1309 rows x 4 columns]

In [ ]:
P1=Adam_class(p1, weights, tickers, year, intial investment simulations=500)

In [ ]:
plot=P1.showplotof simulations()

In [ ]:
st.writew_bokehplots(plot)