In [1]:
from APIs import *
import pandas as pd
from pathlib import Path
import sys

In [2]:
print(sys.path)

['C:\\Users\\boris\\OneDrive\\Documents\\Studies\\ColumbiaBootCamp\\FinTech-Workspace\\Projects\\Project_1_Investment_Advice\\FinTech_Project_1_Investment_Advice\\Boris\\API_calls', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\python39.zip', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\DLLs', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib', 'C:\\Users\\boris\\anaconda3\\envs\\dev', '', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib\\site-packages', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib\\site-packages\\win32', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib\\site-packages\\win32\\lib', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib\\site-packages\\Pythonwin', 'C:\\Users\\boris\\anaconda3\\envs\\dev\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\boris\\.ipython']

In [3]:
# Read the the ny_places_interest.csv file into a DataFrame
portfolios = pd.read_csv(Path("Portfolios.csv"))
portfolios=portfolios.set_index('Ticker')
# Review the DataFrame
portfolios

         Risk Capacity  Risk Tolerance  Benchmark  Cryptomix
Ticker
BTC-USD       0.212815        0.551077   0.532337   0.742584
ETH-USD       0.835128        0.659002   0.572224   0.219586
SQ            0.341948        0.665209   0.672914   0.770282
SHOP          0.564393        0.751846   0.241575   0.368560
TSLA          0.933267        0.041617   0.085270   0.314733
NVDA          0.120167        0.806750   0.233535   0.044073
AAPL          0.132851        0.666972   0.254310   0.385282
GOOG          0.994913        0.097304   0.585566   0.634796
MSFT          0.587720        0.342197   0.038299   0.838989
XOM           0.522416        0.668830   0.276739   0.919309
T             0.937829        0.258753   0.977117   0.938741
JPM           0.216766        0.550176   0.539446   0.447158
TLT           0.432765        0.715202   0.899050   0.263914
IEF           0.761212        0.795183   0.565055   0.003744
VGSH          0.450071        0.036545   0.059156   0.560244
SPY           0.786486        0.197958   0.313707   0.803626
AGG           0.007243        0.445198   0.440449   0.596019

In [4]:
tickers = list(portfolios.index)

In [5]:
tickers

['BTC-USD',
 'ETH-USD',
 'SQ',
 'SHOP',
 'TSLA',
 'NVDA',
 'AAPL',
 'GOOG',
 'MSFT',
 'XOM',
 'T',
 'JPM',
 'TLT',
 'IEF',
 'VGSH',
 'SPY',
 'AGG']

In [6]:
crypto_tickers=[]
for ticker in tickers:
    if len(ticker)>3 and ticker[3]=="-":
        crypto_tickers.append(ticker)

In [7]:
crypto_tickers

['BTC-USD', 'ETH-USD']

In [8]:
other_tickers = [ticker for ticker in tickers if ticker not in crypto_tickers]

In [9]:
other_tickers

['SQ',
 'SHOP',
 'TSLA',
 'NVDA',
 'AAPL',
 'GOOG',
 'MSFT',
 'XOM',
 'T',
 'JPM',
 'TLT',
 'IEF',
 'VGSH',
 'SPY',
 'AGG']

In [10]:
df=get_crypto()

In [11]:
df.index=df.index.date

In [12]:
display(df.head(5))
display(df.tail(5))

            BTC-USD                                                      \
               open     high      low    close       volume trade_count
2019-10-14  8355.00  8420.00  8306.95  8329.95  1000.202435        9398
2019-10-15  8156.52  8171.59  8145.87  8165.08    29.143140         335
2019-10-16  7995.81  7995.81  7937.50  7941.71   707.091075       11460
2019-10-17  8076.94  8117.77  8055.24  8071.36   751.424109       10687
2019-10-18  8071.36  8071.36  7814.08  7954.16  6144.665282       49921

                        ETH-USD                                        \
                   vwap    open    high     low   close        volume
2019-10-14  8349.457967  186.86  188.58  183.13  185.13  16707.530570
2019-10-15  8163.218861  185.17  185.60  176.48  180.67  99608.302647
2019-10-16  7971.132749  174.55  174.62  172.82  172.82   8734.247365
2019-10-17  8084.146720  177.31  177.49  175.58  175.90   7583.984291
2019-10-18  7923.910833  172.96  174.19  171.58  173.63   7304.041174


           trade_count        vwap
2019-10-14        3237  185.728974
2019-10-15       14514  180.708124
2019-10-16        2311  173.910529
2019-10-17        2286  176.598659
2019-10-18        2192  172.830912

             BTC-USD                                                          \
                open      high       low     close        volume trade_count
2023-01-21  22576.08  23375.60  22558.10  22880.78  34894.874014      656817
2023-01-22  22881.30  23082.82  22298.15  22727.69  21878.340882      485753
2023-01-23  22730.15  23180.55  22500.01  23124.50  33863.706436      555285
2023-01-24  23120.99  23159.52  22326.24  22676.47  39765.220323      619079
2023-01-25  22676.47  23824.66  22338.62  23151.97  37439.319545      555925

                          ETH-USD                                            \
                    vwap     open     high      low    close         volume
2023-01-21  22953.543391  1646.10  1680.00  1603.39  1628.03  280759.539903
2023-01-22  22772.094632  1627.84  1664.42  1606.68  1632.69  245670.939864
2023-01-23  22908.943483  1632.70  1648.56  1584.43  1638.18  317669.085165
2023-01-24  22836.993583  1638.13  1638.95  1513.77  1549.58  373220.502840
2023-01-25  22901.575369  1549.55  1640.92  1524.77  1619.95  356879.879197


           trade_count         vwap
2023-01-21      664993  1644.593437
2023-01-22      513706  1634.437343
2023-01-23      660701  1627.677494
2023-01-24      607498  1587.446064
2023-01-25      625416  1576.579246

In [14]:
df1=get_closing_prices(other_tickers)

In [15]:
df1.index=df1.index.date

In [16]:
total_df=df.merge(df1, how='inner', left_index=True, right_index=True)

In [17]:
display(total_df.head())
display(total_df.tail())

            BTC-USD                                                      \
               open     high      low    close       volume trade_count
2019-10-14  8355.00  8420.00  8306.95  8329.95  1000.202435        9398
2019-10-15  8156.52  8171.59  8145.87  8165.08    29.143140         335
2019-10-16  7995.81  7995.81  7937.50  7941.71   707.091075       11460
2019-10-17  8076.94  8117.77  8055.24  8071.36   751.424109       10687
2019-10-18  8071.36  8071.36  7814.08  7954.16  6144.665282       49921

                        ETH-USD                  ...       SPY              \
                   vwap    open    high     low  ...    volume trade_count
2019-10-14  8349.457967  186.86  188.58  183.13  ...  40992668      191854
2019-10-15  8163.218861  185.17  185.60  176.48  ...  48259856      262203
2019-10-16  7971.132749  174.55  174.62  172.82  ...  52268387      243468
2019-10-17  8084.146720  177.31  177.49  175.58  ...  47142725      242876
2019-10-18  7923.910833  172.96  174.19  171.58  ...  64538228      279137

                           AGG                                                 \
                  vwap    open      high     low   close   volume trade_count
2019-10-14  296.136447  112.93  112.9300  112.82  112.92  1716740        7655
2019-10-15  298.786484  112.90  112.9200  112.55  112.57  4168633       12909
2019-10-16  298.452661  112.68  112.7900  112.62  112.75  2430725        9947
2019-10-17  299.346255  112.67  112.8649  112.62  112.72  2320651        8412
2019-10-18  298.443287  112.76  112.9090  112.73  112.80  1454267        7089


                  vwap
2019-10-14  112.887012
2019-10-15  112.627821
2019-10-16  112.714991
2019-10-17  112.759108
2019-10-18  112.821055

[5 rows x 119 columns]

             BTC-USD                                                          \
                open      high       low     close        volume trade_count
2023-01-18  21313.79  21650.21  20370.01  20812.48  33913.652726      648734
2023-01-19  20812.48  21222.00  20660.09  20984.41  24789.695310      510534
2023-01-20  20985.29  22801.00  20865.64  22577.49  33551.658486      711813
2023-01-23  22730.15  23180.55  22500.01  23124.50  33863.706436      555285
2023-01-24  23120.99  23159.52  22326.24  22676.47  39765.220323      619079

                          ETH-USD                    ...       SPY  \
                    vwap     open     high      low  ...    volume
2023-01-18  20976.330249  1587.60  1612.66  1500.32  ...  99651010
2023-01-19  20961.715195  1528.04  1564.61  1513.00  ...  87066127
2023-01-20  21824.837391  1546.99  1677.48  1541.94  ...  91806356
2023-01-23  22908.943483  1632.70  1648.56  1584.43  ...  84187957
2023-01-24  22836.993583  1638.13  1638.95  1513.77  ...  59549719

                                       AGG                                    \
           trade_count        vwap    open     high     low   close   volume
2023-01-18      643581  394.553482  100.76  100.875  100.37  100.73  7779527
2023-01-19      549053  389.264685  100.73  100.730  100.33  100.50  8633859
2023-01-20      505915  392.598891  100.17  100.260   99.89  100.09  6095775
2023-01-23      568843  399.770552   99.80  100.060   99.78   99.84  6573365
2023-01-24      434698  399.936054   99.84  100.320   99.68  100.28  6539095


           trade_count        vwap
2023-01-18       26696  100.664398
2023-01-19       23638  100.504973
2023-01-20       18911  100.069086
2023-01-23       20920   99.871001
2023-01-24       20248  100.146289

[5 rows x 119 columns]

In [18]:
total_df.isnull().mean()

BTC-USD  open           0.0
         high           0.0
         low            0.0
         close          0.0
         volume         0.0
                       ...
AGG      low            0.0
         close          0.0
         volume         0.0
         trade_count    0.0
         vwap           0.0
Length: 119, dtype: float64

In [19]:
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 826 entries, 2019-10-14 to 2023-01-24
Columns: 119 entries, ('BTC-USD', 'open') to ('AGG', 'vwap')
dtypes: float64(87), int64(32)
memory usage: 774.4+ KB

In [ ]:
# Create an empty DataFrame for holding the closing prices
closing_prices_df = pd.DataFrame()
for ticker in tickers:
    closing_prices_df[ticker] = total_df[ticker]['close']

In [ ]:
closing_prices_df.head()

In [ ]:
closing_prices_df=closing_prices_df.drop_duplicates()
closing_prices_df

In [ ]:
daily_returns_df=closing_prices_df.pct_change().dropna()

In [ ]:
daily_returns_df

In [ ]:
portfolios

In [ ]:
p1_df=portfolios.loc[:,'P1']
p1_df=p1_df[p1_df > 0]
p1_df

In [ ]:
p1_df=p1_df.to_frame('weights')

In [ ]:
symbols=list(p1_df.index)
weights=list(p1_df['weights'])
display(symbols)
display(weights)

In [ ]:
my_df=total_df.loc[:,symbols]

In [ ]:
my_df

In [ ]:
portfolios_returns=daily_returns_df.dot(portfolios)

In [ ]:
portfolios_returns

In [ ]:
P1=Adam_class(p1, weights, tickers, year, intial investment simulations=500)

In [ ]:
plot=P1.showplotof simulations()

In [ ]:
st.writew_bokehplots(plot)