In [130]:
from APIs import *
import pandas as pd
from pathlib import Path

In [131]:
# Read the the ny_places_interest.csv file into a DataFrame
portfolios = pd.read_csv(Path("Portfolios.csv"))
portfolios=portfolios.set_index('Ticker')
# Review the DataFrame
portfolios

          P1   P2   P3   P4
Ticker
BTC-USD  0.2  0.0  0.1  0.0
ETH-USD  0.3  0.4  0.3  0.0
T        0.1  0.0  0.0  0.5
XOM      0.0  0.5  0.0  0.4
AAPL     0.3  0.0  0.0  0.0
MSFT     0.1  0.0  0.0  0.0
SQ       0.0  0.0  0.5  0.0
AGG      0.0  0.1  0.0  0.0
SPY      0.0  0.0  0.1  0.1

In [132]:
tickers = list(portfolios.index)

In [133]:
tickers

['BTC-USD', 'ETH-USD', 'T', 'XOM', 'AAPL', 'MSFT', 'SQ', 'AGG', 'SPY']

In [134]:
crypto_tickers=[]
for ticker in tickers:
    if len(ticker)>3 and ticker[3]=="-":
        crypto_tickers.append(ticker)

In [135]:
crypto_tickers

['BTC-USD', 'ETH-USD']

In [136]:
other_tickers = [ticker for ticker in tickers if ticker not in crypto_tickers]

In [137]:
other_tickers

['T', 'XOM', 'AAPL', 'MSFT', 'SQ', 'AGG', 'SPY']

In [138]:
df=get_crypto()

ConnectionError: HTTPSConnectionPool(host='data.alpaca.markets', port=443): Max retries exceeded with url: /v1beta1/crypto/BTCUSD/bars?timeframe=1Day&start=2022-08-18&end=2023-01-23 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C2BF2E4B50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

In [ ]:
df.index=df.index.date

In [ ]:
df

In [ ]:
df1,df2=get_closing_prices(other_tickers)

In [ ]:
df1.index=df1.index.date

In [ ]:
total_df=df.merge(df1, how='inner', left_index=True, right_index=True)

In [139]:
total_df

             BTC-USD                                                          \
                open      high       low     close        volume trade_count
2022-08-18  23383.74  23599.71  22700.00  22789.19   4763.208300       63269
2022-08-18  23379.04  23600.00  22712.22  22787.49  16656.303422      577763
2022-08-18  23418.00  23573.70  22720.30  22825.10     61.915078         603
2022-08-18  23383.00  23588.00  22725.00  22787.00   1466.354200       10621
2022-08-19  22785.91  22836.06  20785.22  21240.00  14143.727125      125223
...              ...       ...       ...       ...           ...         ...
2023-01-20  20985.29  22801.00  20865.64  22577.49  33551.658486      711813
2023-01-20  20984.20  22799.10  20883.20  22577.10   1925.087775       10771
2023-01-23  22719.69  23164.32  22436.55  23113.10   5717.197549      129258
2023-01-23  22730.15  23180.55  22500.01  23124.50  33863.706436      555285
2023-01-23  22721.90  23164.00  22500.10  23098.30   1980.973897        8115

                          ETH-USD                    ...      AGG              \
                    vwap     open     high      low  ...   volume trade_count
2022-08-18  23182.752720  1844.00  1882.00  1806.02  ...  3838685       15666
2022-08-18  23232.073186  1844.31  1883.35  1800.25  ...  3838685       15666
2022-08-18  23313.500938  1870.26  1870.26  1816.74  ...  3838685       15666
2022-08-18  23216.050021  1844.20  1882.40  1805.60  ...  3838685       15666
2022-08-19  21424.311064  1818.27  1823.34  1603.38  ...  4567988       14353
...                  ...      ...      ...      ...  ...      ...         ...
2023-01-20  21824.837391  1546.99  1677.48  1541.94  ...  6095775       18911
2023-01-20  22051.804934  1546.62  1677.00  1542.13  ...  6095775       18911
2023-01-23  22902.078791  1631.67  1648.02  1586.09  ...  6573365       20920
2023-01-23  22908.943483  1632.70  1648.56  1584.43  ...  6573365       20920
2023-01-23  22882.055677  1636.46  1647.99  1586.31  ...  6573365       20920

                           SPY                                                 \
                  vwap    open     high     low   close    volume trade_count
2022-08-18  102.773638  426.86  428.610  425.50  427.89  47948507      331980
2022-08-18  102.773638  426.86  428.610  425.50  427.89  47948507      331980
2022-08-18  102.773638  426.86  428.610  425.50  427.89  47948507      331980
2022-08-18  102.773638  426.86  428.610  425.50  427.89  47948507      331980
2022-08-19  101.981855  425.01  425.260  421.22  422.14  67861630      438953
...                ...     ...      ...     ...     ...       ...         ...
2023-01-20  100.069086  390.10  396.040  388.38  395.88  91806356      505915
2023-01-20  100.069086  390.10  396.040  388.38  395.88  91806356      505915
2023-01-23   99.871001  396.72  402.645  395.72  400.63  84187957      568843
2023-01-23   99.871001  396.72  402.645  395.72  400.63  84187957      568843
2023-01-23   99.871001  396.72  402.645  395.72  400.63  84187957      568843


                  vwap
2022-08-18  427.137042
2022-08-18  427.137042
2022-08-18  427.137042
2022-08-18  427.137042
2022-08-19  423.097019
...                ...
2023-01-20  392.598891
2023-01-20  392.598891
2023-01-23  399.770552
2023-01-23  399.770552
2023-01-23  399.770552

[385 rows x 63 columns]

In [140]:
# Create an empty DataFrame for holding the closing prices
closing_prices_df = pd.DataFrame()
for ticker in tickers:
    closing_prices_df[ticker] = total_df[ticker]['close']

In [145]:
closing_prices_df.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [143]:
closing_prices_df=closing_prices_df.drop_duplicates()
closing_prices_df

AttributeError: 'NoneType' object has no attribute 'drop_duplicates'

In [142]:
daily_returns_df=closing_prices_df.pct_change().dropna()

AttributeError: 'NoneType' object has no attribute 'pct_change'

In [129]:
daily_returns_df

,BTC-USD,ETH-USD,T,XOM,AAPL,MSFT,SQ,AGG,SPY
2022-08-18,-0.000075,0.000005,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2022-08-18,0.001650,0.000517,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2022-08-18,-0.001669,-0.000451,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2022-08-19,-0.067890,-0.094035,0.00000,-0.003179,-0.015102,-0.013854,-0.067235,-0.007010,-0.013438
2022-08-19,0.000231,-0.000085,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
2023-01-20,0.000505,0.000310,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-01-20,-0.000017,0.001689,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-01-23,0.023741,-0.006774,-0.00676,-0.005205,0.023500,0.009824,0.072216,-0.002498,0.011999
2023-01-23,0.000493,0.000287,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-01-23,-0.001133,-0.000299,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [177]:
portfolios

          P1   P2   P3   P4
Ticker
BTC-USD  0.2  0.0  0.1  0.0
ETH-USD  0.3  0.4  0.3  0.0
T        0.1  0.0  0.0  0.5
XOM      0.0  0.5  0.0  0.4
AAPL     0.3  0.0  0.0  0.0
MSFT     0.1  0.0  0.0  0.0
SQ       0.0  0.0  0.5  0.0
AGG      0.0  0.1  0.0  0.0
SPY      0.0  0.0  0.1  0.1

In [178]:
p1_df=portfolios.loc[:,'P1']
p1_df=p1_df[p1_df > 0]
p1_df

Ticker
BTC-USD    0.2
ETH-USD    0.3
T          0.1
AAPL       0.3
MSFT       0.1
Name: P1, dtype: float64

In [179]:
p1_df=p1_df.to_frame('weights')

In [180]:
symbols=list(p1_df.index)
weights=list(p1_df['weights'])
display(symbols)
display(weights)

['BTC-USD', 'ETH-USD', 'T', 'AAPL', 'MSFT']

[0.2, 0.3, 0.1, 0.3, 0.1]

In [181]:
my_df=total_df.loc[:,symbols]

In [182]:
my_df

             BTC-USD                                                          \
                open      high       low     close        volume trade_count
2022-08-18  23383.74  23599.71  22700.00  22789.19   4763.208300       63269
2022-08-18  23379.04  23600.00  22712.22  22787.49  16656.303422      577763
2022-08-18  23418.00  23573.70  22720.30  22825.10     61.915078         603
2022-08-18  23383.00  23588.00  22725.00  22787.00   1466.354200       10621
2022-08-19  22785.91  22836.06  20785.22  21240.00  14143.727125      125223
...              ...       ...       ...       ...           ...         ...
2023-01-20  20985.29  22801.00  20865.64  22577.49  33551.658486      711813
2023-01-20  20984.20  22799.10  20883.20  22577.10   1925.087775       10771
2023-01-23  22719.69  23164.32  22436.55  23113.10   5717.197549      129258
2023-01-23  22730.15  23180.55  22500.01  23124.50  33863.706436      555285
2023-01-23  22721.90  23164.00  22500.10  23098.30   1980.973897        8115

                          ETH-USD                    ...      AAPL  \
                    vwap     open     high      low  ...    volume
2022-08-18  23182.752720  1844.00  1882.00  1806.02  ...  62290075
2022-08-18  23232.073186  1844.31  1883.35  1800.25  ...  62290075
2022-08-18  23313.500938  1870.26  1870.26  1816.74  ...  62290075
2022-08-18  23216.050021  1844.20  1882.40  1805.60  ...  62290075
2022-08-19  21424.311064  1818.27  1823.34  1603.38  ...  70346195
...                  ...      ...      ...      ...  ...       ...
2023-01-20  21824.837391  1546.99  1677.48  1541.94  ...  80246596
2023-01-20  22051.804934  1546.62  1677.00  1542.13  ...  80246596
2023-01-23  22902.078791  1631.67  1648.02  1586.09  ...  81782578
2023-01-23  22908.943483  1632.70  1648.56  1584.43  ...  81782578
2023-01-23  22882.055677  1636.46  1647.99  1586.31  ...  81782578

                                       MSFT                           \
           trade_count        vwap     open     high     low   close
2022-08-18      545655  174.136650  290.189  291.910  289.08  290.17
2022-08-18      545655  174.136650  290.189  291.910  289.08  290.17
2022-08-18      545655  174.136650  290.189  291.910  289.08  290.17
2022-08-18      545655  174.136650  290.189  291.910  289.08  290.17
2022-08-19      573126  172.230161  288.900  289.250  285.56  286.15
...                ...         ...      ...      ...     ...     ...
2023-01-20      552231  136.375340  234.855  240.740  234.51  240.22
2023-01-20      552231  136.375340  234.855  240.740  234.51  240.22
2023-01-23      720202  141.211585  241.100  245.165  239.65  242.58
2023-01-23      720202  141.211585  241.100  245.165  239.65  242.58
2023-01-23      720202  141.211585  241.100  245.165  239.65  242.58


              volume trade_count        vwap
2022-08-18  17186192      220665  290.530800
2022-08-18  17186192      220665  290.530800
2022-08-18  17186192      220665  290.530800
2022-08-18  17186192      220665  290.530800
2022-08-19  20570033      242758  286.831665
...              ...         ...         ...
2023-01-20  35529808      364052  238.213442
2023-01-20  35529808      364052  238.213442
2023-01-23  31959175      413797  242.750685
2023-01-23  31959175      413797  242.750685
2023-01-23  31959175      413797  242.750685

[385 rows x 35 columns]

In [184]:
portfolios_returns=daily_returns_df.dot(portfolios)

In [185]:
portfolios_returns

                  P1        P2        P3        P4
2022-08-18 -0.000013  0.000002 -0.000006  0.000000
2022-08-18  0.000485  0.000207  0.000320  0.000000
2022-08-18 -0.000469 -0.000180 -0.000302  0.000000
2022-08-19 -0.047704 -0.039904 -0.069961 -0.002615
2022-08-19  0.000021 -0.000034 -0.000002  0.000000
...              ...       ...       ...       ...
2023-01-20  0.000194  0.000124  0.000143  0.000000
2023-01-20  0.000503  0.000676  0.000505  0.000000
2023-01-23  0.010072 -0.005562  0.037650 -0.004262
2023-01-23  0.000185  0.000115  0.000135  0.000000
2023-01-23 -0.000316 -0.000120 -0.000203  0.000000

[384 rows x 4 columns]