In [1]:
from yahoo_api import *

In [2]:
tickers_index=['BTC-USD','ETH-USD','SQ','SHOP','TSLA','NVDA','AAPL','GOOG','MSFT','SPY','AGG']
capacity_series=pd.Series([0.0,0.0,0.0,0.0,0.0,0.2,0.3,0.3,0.2,0.0,0.0])
tolerance_series=pd.Series([0.0,0.0,0.0,0.0,0.2,0.2,0.2,0.2,0.2,0.0,0.0])
benchmark_series=pd.Series([0.0,0.0,0.0,0.0,0.0,0.2,0.3,0.3,0.2,0.6,0.4])
cryptomix_series=pd.Series([0.05,0.05,0.3,0.3,0.3,0.2,0.3,0.3,0.2,0.0,0.0])
test_dataframe=pd.DataFrame(data=[capacity_series,tolerance_series,benchmark_series,cryptomix_series]).T
test_dataframe.index=tickers_index
test_dataframe.columns=['Risk Capacity','Risk Tolerance', 'Benchmark', 'Cryptomix']

In [3]:
test_dataframe

         Risk Capacity  Risk Tolerance  Benchmark  Cryptomix
BTC-USD            0.0             0.0        0.0       0.05
ETH-USD            0.0             0.0        0.0       0.05
SQ                 0.0             0.0        0.0       0.30
SHOP               0.0             0.0        0.0       0.30
TSLA               0.0             0.2        0.0       0.30
NVDA               0.2             0.2        0.2       0.20
AAPL               0.3             0.2        0.3       0.30
GOOG               0.3             0.2        0.3       0.30
MSFT               0.2             0.2        0.2       0.20
SPY                0.0             0.0        0.6       0.00
AGG                0.0             0.0        0.4       0.00

In [6]:
historical_prices=historical_prices(test_dataframe)

Waiting 100 seconds to avoid overloading the API

In [10]:
historical_prices.tail()

             BTC-USD                                             ETH-USD  \
                open      high       low     close       volume     open
date
01-20-2023  22677.43  23282.35  22511.83  22777.63  32442278429  1659.71
01-23-2023  22929.63  23134.01  22549.74  22636.47  26405069715  1627.85
01-24-2023  22639.27   23722.1  22406.08  23117.86  30685366709  1556.81
01-25-2023  23108.96  23237.08  22911.37  23032.78  26357839322  1611.08
01-26-2023  23024.89   23061.6  22672.64  22790.65  26097217536  1602.44

                                                    ...     SPY          \
               high      low    close       volume  ...    open    high
date                                                ...
01-20-2023  1674.18  1626.81  1627.12   8859250310  ...   390.1  396.04
01-23-2023  1639.72  1551.39   1556.6   8180274691  ...  396.72  402.65
01-24-2023  1632.24   1530.8  1611.71  10598973448  ...  398.88  401.15
01-25-2023   1626.2   1586.6  1603.11   8395315241  ...  395.95   400.7
01-26-2023  1605.49  1565.96  1568.61   8671653888  ...  403.13  404.92

                                         AGG
               low   close    volume    open    high     low   close   volume
date
01-20-2023  388.38  395.88  91544900  100.17  100.26   99.89  100.09  6095800
01-23-2023  395.72  400.63  84178800    99.8  100.06   99.78   99.84  6573200
01-24-2023  397.64   400.2  59524900   99.84  100.32   99.68  100.28  6538600
01-25-2023  393.56  400.35  84800300  100.26  100.47   100.1   100.4  5431000
01-26-2023  400.03  404.75  72053800  100.33  100.46  100.07  100.23  5399100

[5 rows x 55 columns]

In [8]:
weighted_returns(historical_prices,weights_df=test_dataframe)

            Risk Capacity  Risk Tolerance  Benchmark  Cryptomix
date
11-09-2017      -0.007878       -0.007733  -0.010346  -0.013285
11-10-2017       0.007019        0.008012   0.005225   0.026786
11-13-2017      -0.004956        0.003888  -0.004398   0.015496
11-14-2017      -0.002779       -0.005560  -0.003769  -0.005902
11-15-2017      -0.011853       -0.008406  -0.014086  -0.002025
...                   ...             ...        ...        ...
01-20-2023       0.042882        0.045071   0.052428   0.098016
01-23-2023       0.030027        0.041218   0.036227   0.098826
01-24-2023      -0.002604       -0.001440  -0.001485  -0.011871
01-25-2023      -0.009489       -0.005769  -0.008785   0.023719
01-26-2023       0.023078        0.041020   0.028995   0.062277

[1311 rows x 4 columns]